//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace udnz.com.VSExtensions.QuickLauncher.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("udnz.com.VSExtensions.QuickLauncher.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can not open this item: {0} 的本地化字符串。
        /// </summary>
        internal static string CanNotOpen {
            get {
                return ResourceManager.GetString("CanNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close this window after file opening 的本地化字符串。
        /// </summary>
        internal static string CloseWindowAfterFileOpening {
            get {
                return ResourceManager.GetString("CloseWindowAfterFileOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ColumnHead_Name {
            get {
                return ResourceManager.GetString("ColumnHead_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string ColumnHead_Path {
            get {
                return ResourceManager.GetString("ColumnHead_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open file: {0} 的本地化字符串。
        /// </summary>
        internal static string FileOpened {
            get {
                return ResourceManager.GetString("FileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        internal static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the keyword of file name, then press Enter/Return/Down/Tab 的本地化字符串。
        /// </summary>
        internal static string KeyToolTip {
            get {
                return ResourceManager.GetString("KeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} item(s) found 的本地化字符串。
        /// </summary>
        internal static string NItemsFound {
            get {
                return ResourceManager.GetString("NItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing found 的本地化字符串。
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open a solution/project first 的本地化字符串。
        /// </summary>
        internal static string PleaseOpenSolution {
            get {
                return ResourceManager.GetString("PleaseOpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Launcher For Files 的本地化字符串。
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
